# this is the port on which our random-greeting-service will run
server:
  port: 2121

# allow for RefreshScope
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource:
    url: jdbc:mysql://localhost:3306/moto_inventory?useSSL=false
    username: root
    password: rootroot
    initialization-mode: always
